accounts/urls.py
from django.urls import path
from .views import Signuppage

urlpatterns=[
    path('signup/',Signuppage.as_view(), name='signup')
]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('account/',include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('',include('news.urls')),
    path('blog/',include('news.urls')),
]

news/urls.py
from django.urls import path
from .views import (
    Blogpage,
    Detailpage,
    Blogcreatepage,
    Updatepage,
    Deletepage,)

urlpatterns=[
    path('new/<int:pk>/detete',Deletepage.as_view(),name='delete'),
    path('new/<int:pk>/edit',Updatepage.as_view(), name='edit' ),
    path('new/',Blogcreatepage.as_view(),name='new'),
#    path('post/',Homepage.as_view(),name='home'),
    path('',Blogpage.as_view(),name='blog'),
    path('new/<int:pk>/',Detailpage.as_view(),name='detail'),
]

accounts/models.py
from django.db import models

# Create your models here.

news/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Posts(models.Model):
    title=models.CharField(max_length=100)
    izoh=models.TextField()

    def __str__(self):
        return self.title

class Blog(models.Model):
    title=models.CharField(max_length=100)
    author=models.ForeignKey('auth.User',on_delete=models.CASCADE)
    izoh=models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return  reverse('detail',args=[str(self.pk)])

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView
from django.urls import reverse_lazy

# Create your views here.

class Signuppage(CreateView):
    form_class =UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

news/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView
from  .models import Posts, Blog
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy

# Create your views here.

#class Homepage(ListView):
#    model = Posts
#    template_name = 'home.html'

class Blogpage(ListView):
    model = Blog
    template_name = 'blog.html'

class Detailpage(DetailView):
    model = Blog
    template_name = 'detail.html'

class Blogcreatepage(CreateView):
    model = Blog
    template_name = 'new_det.html'
    fields = ['title','author','izoh']

class Updatepage(UpdateView):
    model = Blog
    template_name = 'update.html'
    fields = ['title','izoh']

class Deletepage(DeleteView):
    model=Blog
    template_name = 'delete.html'
    success_url = reverse_lazy('blog')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
    <link rel="stylesheet" href="{% static 'css/base.css'%}">
</head>
<body>
  <header>
    <h1><a href="{% url 'blog' %}"> My Blog </a></h1>
  </header>
  {% if user.is_autheticated %}
    <p>Xush kelibsiz, {{user.username}}!</p>
    <p><a href="{% url 'logout' %}">Chiqib ketish</a></p>
  {% else %}
    <p><a href="{% url 'login' %}">Saytga kirish</a>|
    <a href="{% url 'signup' %}">Ro'yxatdan o'tish</a></p>

  <div>
  {% endif %}
    {% block content %}
    {% endblock content %}
  </div>
  <footer>
      <h2><a href="{% url 'new' %}">Yangi blog yozish </a></h2>
  </footer>
</body>
</html>

templates/blog.html
{% extends 'base.html' %}
{% block content %}
    {% for i in object_list %}
        <div class="post-entry">
            <h2><a href="{% url 'detail'  i.pk %}">{{i.title}}</a></h2>
            <p>{{i.izoh}}</p>

        </div>
    {% endfor %}
{% endblock content %}

templates/delete.html
{% extends 'base.html' %}
{% block content %}
<h2> Blogni o'chirish </h2>
  <form action="" method="post">{% csrf_token %}
  <h3>"{{i.title}}" rostdan ham o'chirilsinmi</h3>
  <input type="submit" value="O'chirish">
</form>
{% endblock content %}

templates/detail.html
{% extends 'base.html' %}
{% block content %}


      <h1>{{i.title}}</h1>
        <h2>{{i.author}}</h2>
      <p>{{i.izoh}}</p>


{% endblock content %}

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Yangiliklar</title>
</head>
<body>
    <h1>Kun yangiliklari</h1>
    <ul>
        {% for i in posts_list %}
        <li><h2>{{i.title}}</h2><br>{{i.izoh}}</li></br>
        {% endfor %}
    </ul>

</body>
</html>

templates/new_det.html
{% extends 'base.html' %}

{% block content %}
   <h1>Kun yangiliklari </h1>
        <href action="" method="post">{% csrf_token %}
            {{ from.as_p }}
            <input type="submit" value="Saqlash">
        </href>
{% endblock content %}

templates/update.html
{% extends 'base.html'%}
{% block content %}
    <h1>Yangilash</h1>
    <form action="" method="post"></form>{% csrf_token%}
    {{ form.as_p}}
    <div>
        <input type="submit" value="Saqlash">
    </div>
{% endblock content %}